### ISSUE TITLE
Catch the NaN error that occurs when histograms are not well-populated

### ISSUE THREAD

**Issue by mrshirts** [shirtsgroup/checkensemble#2]
When distributions are chosen poorly, it's very likely the ratio of the histograms will be undefined, as the denominator will be zero. This needs to be caught with a proper warning.

**Comment by mrshirts** [comment]
The issues show up as warnings:

checkensemble/checkensemble/checkensemble.py:910: RuntimeWarning: divide by zero encountered in log
  ratio = numpy.log(hlist[1]/hlist[0]) # this should have the proper exponential distribution
checkensemble/checkensemble/checkensemble.py:911: RuntimeWarning: invalid value encountered in divide
  dratio = numpy.sqrt((dhlist[0]/hlist[0])**2 + (dhlist[1]/hlist[1])**2)
checkensemble/checkensemble/checkensemble.py:910: RuntimeWarning: divide by zero encountered in divide
  ratio = numpy.log(hlist[1]/hlist[0]) # this should have the proper exponential distribution

**Comment by ptmerz** [comment]
Migrated: https://github.com/shirtsgroup/physical-validation/issues/1
