### ISSUE TITLE
Get a nice setup.py and conda install system set up

### ISSUE THREAD

**Issue by mrshirts** [shirtsgroup/checkensemble#3]
Make it easier to install, either through conda, or pip.

Try to figure out where to put the examples and example scripts. What is the best practice for placing scripts and example files?

**Comment by mrshirts** [comment]
- [ ] write a setup.py that puts modules where modules go, and data/executables where they go
- [ ] Write nose tests? 
- [ ] set up up CI?

**Comment by mrshirts** [comment]
So, I've done some reading so far on the best way to approach this. 

There are three basic things to do, each of which might imply some reorganization.  I've actually started some more of it in the reorganization branch (https://github.com/shirtsgroup/checkensemble/tree/reorganization), but still lots to do.

1. Setup.py.  The main questions are where to put:
    a. the executables (currently in examples, in the reorganization branch in bin/), including 
         i. analyze-md.py (analyzes two md files), 
         ii. analyze-replica.py (analyzes a set of replica exchange simulations),
         iii. harmonic.py (generates a NVT ensemble from a harmonic oscillator toy system, and runs checkensemble on this system)
         iv. harmonic_pressure.py (generates an NPT ensemble with a pressure-dependent force constant, and runs checkensemble)
         v. harmonic_mu.py (runs a NV\mu simulation with a varying number of harmonic oscillators, and runs checkensembe)
    b. Where to put the example_data files (sample MD run files, etc).
    c. Where to put the documentation about using the examples (output files, output pdfs, list of sample exams)
    d. For the main modules, they get installed in site-packages automatically, so no question there.
 
    for 1.a. we should probably rewrite the command lines such that can function as modules, with command wrappers.  We could use the layout or https://gehrcke.de/2014/02/distributing-a-python-command-line-application/, for how to install them as executables.  The three harmonic commands can then be used as tests (more for another issue!)
    for 1.b. it's a bit more complicated.  With a simple setup.py, we could leave them exactly where the were (people will download it, and can then just run examples as they see fit in the download directory. 
     gor 1.c. We can move the descriptions into a doc directory.  It might also be a good place to put the example outputs, and even the run scripts (in a sub directory, so the documentation doesn't get cluttered).

2. doing a Python Package (pip) install.

   This is probably the simplest way to do install.  It does mean we need to decide where to put the example files.  I'm not really sure.  We could prompt on install where to put them, but that seems to be deprecated in pip. I haven't resolved this.  Some more documentation here: https://packaging.python.org/distributing/

3. setting it up for a conda install. 
    A bit more complicated.  I think because of the number of md simulation files going into omnia, it probably would be good to put this here.

Note that to be incorporated into (at least by April 1st), we don't need to solve all of these problems, as GROMACS will only be calling the modules with new scripts.

**Comment by mrshirts** [comment]
ParmEd (https://github.com/ParmEd) has a decent setup.py -- also has some examples, like we have -- though it just leaves them in the install directory, they don't seem to be otherwise installed.

**Comment by ptmerz** [comment]
checkensemble will not become installable - but the [physical validation suite](https://github.com/shirtsgroup/physical-validation) should. Migrated to https://github.com/shirtsgroup/physical-validation/issues/2
