### ISSUE TITLE
Deal with the FutureWarning below

### ISSUE THREAD

**Issue by mrshirts** [shirtsgroup/checkensemble#5]
checkensemble/checkensemble/checkensemble.py:1299: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if ((g == None) or (g[0]==1 and g[1]==1)):

**Comment by ptmerz** [comment]
`==` can be overloaded, to be e.g. element-wise. `[a,b] == None` is then equivalent to `[a==None,b==None]`.
Fix: As `None` is a Singleton, and `is` cannot be overloaded, use `is None` instead of `== None` (or `is not None` instead of `!= None`). Replaced this in all python scripts.
